# Generated by Django 5.0.4 on 2024-08-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_address_country_alter_orderline_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='street_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
