# Generated by Django 5.0.4 on 2024-09-30 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_writer_publisher_vendor_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='api.publisher'),
        ),
        migrations.AddField(
            model_name='product',
            name='writer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='api.writer'),
        ),
    ]
